### ISSUE TITLE
Upgrading to 0.30.1 causes an error

### ISSUE THREAD

**Issue by mehta-ankit** [jaegertracing/helm-charts#124]
I tried using the chart version 0.30.1, and it throws an error:
```
Error: YAML parse error on /charts/jaeger/templates/spark-cronjob.yaml: error converting YAML to JSON: yaml: line 44: could not find expected ':'
 helm.go:75: [debug] error converting YAML to JSON: yaml: line 44: could not find expected ':'
```
I think its related to: https://github.com/jaegertracing/helm-charts/pull/119
 cc @naseemkullah

**Comment by mehta-ankit** [comment]
Using `helm template` i can see an empty array just sitting there between environment variables
![image](https://user-images.githubusercontent.com/22157398/84579996-e36a7980-ada0-11ea-92d8-0ea2c853e42a.png)

Looks like this is the issue.

**Comment by naseemkullah** [comment]
Thanks for raising this @mehta-ankit!

this will be fixed now via https://github.com/jaegertracing/helm-charts/pull/121/commits/54f6f26b0787e8ee5c928dd68bc71b570de96ec2

Do you mind taking a look at the PR and approving it? Since this includes a hot fix I might not wait for official maintainers @pavelnikolov and @dvonthenen to approve.
