### ISSUE TITLE
[Jaeger] Deployment strategy for Query and Collector hard coded to Recreate.

### ISSUE THREAD

**Issue by bhiravabhatla** [jaegertracing/helm-charts#176]
Deployement strategy for Query and Collector deployment hard coded to Recreate. Any reason why it cant be Rolling?

https://github.com/jaegertracing/helm-charts/blob/dab35966cbe4a17f56ea501c63fdaf32712adc2f/charts/jaeger/templates/collector-deploy.yaml#L22

https://github.com/jaegertracing/helm-charts/blob/dab35966cbe4a17f56ea501c63fdaf32712adc2f/charts/jaeger/templates/query-deploy.yaml#L20

Could we at least have them templatized.

**Comment by naseemkullah** [comment]
Thanks for flagging @bhiravabhatla. AFAIK, recreate is only useful for single replica deployments that mount a PVC. Not sure of other use cases or why it was the case for query/collector. Let's try removing them altogether from the template so that it defaults to RollingUpgrade which seems more appropriate. Up for a PR?
