### ISSUE TITLE
support the ingressClassName field on the ingress

### ISSUE THREAD

**Issue by KqLLL** [jaegertracing/helm-charts#236]
```yaml
Before the IngressClass resource and ingressClassName field were added in Kubernetes 1.18, Ingress classes were specified with a kubernetes.io/ingress.class annotation on the Ingress.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
spec:
  ingressClassName: "nginx"
  defaultBackend:
    service:
      name: test
      port:
        number: 80

example:
  {{- if .Values.hotrod.ingress.ingressClassName }}
      ingressClassName: { { .Values.hotrod.ingress.ingressClassName | quote } }
  {{- end }}

**Comment by cikupin** [comment]
Up... We need this field

**Comment by mehta-ankit** [comment]
This is not as straightforward I believe.  
If you use ingressClassName field and IngressClass resource does not exist on the K8s cluster, the ingress would fail to come up (it will error out).

Options are:

1) We can continue to support the annotation until its deprecated by K8s. If someone needs to use ingressClassName they can create their own Ingress rather than relying on the one that comes from the chart (disable it by setting .Values.hotrod.ingress.enabled to false)

2) We check for existence for IngressClass resource somehow and then add the field otherwise add the annotation (i don't like this as it puts the burden on the helm chart vs the developer deploying the resources).

🤔

**Comment by naseemkullah** [comment]
Would replacing our ingress template with `helm create`'s ([this](https://github.com/helm/helm/blob/9fafb4ad6811afb017cc464b630be2ff8390ac63/pkg/chartutil/create.go#L215-L276)) work?

**Comment by mehta-ankit** [comment]
> Would replacing our ingress template with `helm create`'s ([this](https://github.com/helm/helm/blob/9fafb4ad6811afb017cc464b630be2ff8390ac63/pkg/chartutil/create.go#L215-L276)) work?

Yes this type of check would work in theory and If i understand it correctly its only checking for value to exist and K8s version to be > 1.18
```
{{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
```
but there is a possibility for K8s version to be > 1.18 but IngressClass resource to not exist. In those clusters it will fail. But yea that case can be ignored as non standard 🤷🏽 , maybe in that case dev's can use their own ingress vs what comes from the chart.

**Comment by cikupin** [comment]
I think that you can try an approach like what Grafana do. It provides `ingressClassName` spec while also allowing `kubernetes.io/ingress.class` annotation to be added as an alternative option.

https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/ingress.yaml#L28

https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L187
