### ISSUE TITLE
[jaeger] to helm3

### ISSUE THREAD

**Issue by naseemkullah** [jaegertracing/helm-charts#5]
Bump chart api version to v2, move requirements.yaml into chart.yaml and any other necessary adjustments

**Comment by scottrigby** [comment]
Since Helm 2 has a [1 year deprecation period](https://helm.sh/blog/2019-10-22-helm-2150-released/#helm-2-support-plan), you may want to keep apiVersion v1 charts around till then (Nov 13, 2020). It's up to you whether you want to require Helm 3 of course, but this is the official deprecation period.

**Comment by arpitjindal97** [comment]
I think we should upgrade it to v2. It will be easier for others to do modifications in exisitng chart.

**Comment by naseemkullah** [comment]
Alright, we will wait until Nov 13, 2020)
