### ISSUE TITLE
[Feature]: Support Jaeger-v2 Helm Chart

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/helm-charts#534]
### Requirement

Once Jaeger-v2 (https://github.com/jaegertracing/jaeger/issues/4843) reaches production readiness and feature parity, we may want to support it in the helm chart.

### Problem

Jaeger-v2 is based on OpenTelemetry Collector and uses completely different configuration mechanism:
  * all configuration is done via config files, not CLI flags or env vars (although some env vars are supported by telemetry SDKs)
  * it is a single binary that can be deployed into different roles (collector, query, etc.) also based on configuration, but in this case with structural config changes, not just tweaking parameters

### Proposal

I would like to hear what maintainers of this repo think about the best approach. Can we come up with a roadmap of how jaeger-v2 could be supported? Is there some common approach we can use with OTEL (https://github.com/open-telemetry/opentelemetry-helm-charts)?

Parallel ticket for Operator: https://github.com/jaegertracing/jaeger-operator/issues/2411

### Open questions

* Is it worth maintaining both helm charts and operator?

**Comment by Stevenpc3** [comment]
We are venturing into using operators.  I mentioned before we deploy to environments where we don't have control over the Paas we run on or full permissions, but under agreements we expect to be able to apply the CRDs to the cluster then we will likely be able to run operators via namespace restrictions.  This is good, but we will still require helm charts.  This would mean we would expect to be able to change over to using the jaeger-operator helm chart https://github.com/jaegertracing/helm-charts/tree/main/charts/jaeger-operator in the future.

As we move into a more GitOps approach we will be using ArgoCD now so applying configs is more simple.  But we have various environments that get more and more restricted as we proceed right.  So there is always a transition period from updating new processes.

I can only thank you for your efforts and your tools and offer a suggestion that deprecation goes a long way towards helping us and others move towards new capabilities, but those capabilities must work or we become stuck in an EOL product because we can't move forward on occasion due to product issues.  So, even if the plan is to NOT support certain items... having a deprecation roadmap would be a great option.

**Comment by yurishkuro** [comment]
closing as duplicate of #610 (moved from Jaeger repo)

**Comment by Stevenpc3** [comment]
I know this is closed, but I feel I never answered the question correctly as perhaps I didn't fully understand. 

This threw me off

![Image](https://github.com/user-attachments/assets/19fda59b-1938-46d8-a72e-d2e0010ce278)

The answer is yes!  Here are some great examples of products that offer a helm chart to deploy their operators that we now use.  Some are still being worked on and there are CRD concerns about multiple versions and being up to date etc that are covered in kube docs and 1 and 2 below handle pretty well.

1. https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
2. https://github.com/elastic/cloud-on-k8s/tree/main/deploy
3. https://github.com/cloudnative-pg/charts
