### ISSUE TITLE
[jaeger] Give user more unlimited config options for storage

### ISSUE THREAD

**Issue by naseemkullah** [jaegertracing/helm-charts#74]
https://github.com/jaegertracing/helm-charts/blob/2f60c580bd4729b18a3173d7a44f8eeafafc481d/charts/jaeger/values.yaml#L18-L44 is not scalable as additional config options get added/removed from upstream jaeger.

It would be great to be able to provide any config options by a variety of means the user can choose from (any or a mix of the following: env vars, env vars from secrets, env vars from configmaps, comman line options).

This has been prompted by consistent PRs such as https://github.com/jaegertracing/helm-charts/pull/73 and https://github.com/jaegertracing/helm-charts/pull/65 to bubble up config options.

**Comment by vipinvkmenon** [comment]
Based on this particular line from the documentation “In order to provide configuration parameters via environment variables, find the respective command line option and convert its name to UPPER_SNAKE_CASE” and considering as more and more flags and features would be coming in.. would it be nice to provide a support on the chart to accept additional environment variables?

more configuration freedom as well☺️

**Comment by naseemkullah** [comment]
💯 

We will allow additional env vars as well as command line options (user can take their pick).

**Comment by naseemkullah** [comment]
Closed via #75
